POST  http://localhost:3005/api/auth/register HTTP/1.1
content-type: application/json

{
    "username": "lala",
    "email": "lal@gmail.com",
    "password": "patopato"
}

###

POST  http://localhost:3005/api/auth/login HTTP/1.1
content-type: application/json

{
    "username": "lala",
    "password": "patopato"
}

###

PUT  http://localhost:3005/api/users/61820d92cf33d909ae4150a0 HTTP/1.1
content-type: application/json

{
    "username": "lal",
}

###